services:
  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./DB/init.sql:/init.sql
    entrypoint: >
      /bin/bash -c "
        sleep 20;
        /opt/mssql-tools/bin/sqlcmd -S db -U sa -P YourStrong@Passw0rd -d master -i /init.sql
      "
    networks:
      - viebook-net
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: viebook-db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1443:1433"
    networks:
      - viebook-net
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: VieBook.BE/Dockerfile
    image: devhoanghai/viebook-backend:latest
    container_name: viebook-api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=VieBook;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    ports:
      - "5757:8080"
    networks:
      - viebook-net

  frontend:
    build:
      context: .
      dockerfile: VieBook.FE/Dockerfile
    image: devhoanghai/viebook-frontend:latest
    container_name: viebook-fe
    depends_on:
      - backend
    ports:
      - "3008:80"
    networks:
      - viebook-net

networks:
  viebook-net:
    driver: bridge
volumes:
  sql_data:
