# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  test:
    # Specify the execution environment for .NET testing
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

    # Add steps to the job
    # See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#steps-overview & https://circleci.com/docs/reference/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Restore dependencies"
          command: |
            cd VieBook.BE
            dotnet restore
      - run:
          name: "Build solution"
          command: |
            cd VieBook.BE
            dotnet build --no-restore
      - run:
          name: "Run tests"
          command: |
            cd VieBook.BE
            dotnet test --no-build --verbosity normal --logger "console;verbosity=detailed"
  build-and-push:
    environment:
      DOCKER_IMAGE: devhoanghai/viebook
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker_username: DOCKER_USERNAME
          docker_password: DOCKER_PASSWORD
      - run:
          name: Build with docker-compose
          command: |
            docker-compose -f docker-compose.yaml build
      - run:
          name: Push image to Docker Hub
          command: |
            docker-compose -f docker-compose.yaml push

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  test-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
